### ISSUE TITLE
num_arrivals attribute of Queuesever is not correct 

### ISSUE THREAD

**Issue by jeroenburgt** [djordon/queueing-tool#65]
When simulating a queue for 5 arrivals and getting the status of the queue, I get the following:

`Out[22]: QueueServer:0. Servers: 4, queued: 0, arrivals: [5, 6], departures: 3, next time: 0.2`

The arrivals attribute dispays [5, 6]. According to the documentation this is: 

> 

num_arrivals | (list) A list with two entries. The first slot is the total number of arrivals, while the second slot is the number of arrivals from outside the network.
-- | --

Based on this definition I expected both number to be 5 as I am using the Queuesever standalone and there will only be arrivals from outside the network.

**Comment by djordon** [comment]
Oh interesting. I think I may know what the issue is, but to confirm, would you mind posting the steps that you took to get to this state, so that I may reproduce it?

**Comment by jeroenburgt** [comment]
This is the code I ran to get to this state:
```
import queueing_tool as qt
import numpy as np

arr_rate = 30
tp_per_min = 10

arr_f = lambda t: t + 1 / arr_rate
ser_f = lambda t: t + np.random.exponential(1 / tp_per_min)
q = qt.queues.QueueServer(4, AgentFactory=qt.queues.GreedyAgent, arrival_f=arr_f,
                          service_f=ser_f, collect_data=True)

q.set_active()
q.simulate(nA=5)
```

**Comment by djordon** [comment]
Thanks, I think I know what the issue is. I'll cook up a fix.

**Comment by djordon** [comment]
Okay, so I took some time to look into this again. I think that the returned value is actually correct, but the description doesn't explain the meaning of that slot.

After an arrival to a `QueueServer` (assuming it is active), a new one is created and slotted to arrive sometime in the future, with the arrival time determined by the `arrival_f` and the current time. This new agent hasn't actually arrived yet, but we count this arrival in the second slot of `num_arrivals`.

So this leads me to think that the language used in the docs is at best confusing. For a standalone `QueueServer`, all arrivals are from outside the network and they are generated by the `QueueServer` using the supplied `AgentFactory`. The first slot in `num_arrivals` tracks how many arrivals are seen up until the current time, while the second slot tracks arrivals generated by the `QueueServer` that we know about, including those in the future.

So this issue is more of a documentation issue that I hope to get to this week.
