### ISSUE TITLE
Change queue discipline

### ISSUE THREAD

**Issue by michalplat** [djordon/queueing-tool#67]
Hi. Is there any way to change queue discipline? For example instead using FIFO use Shortest Job Next or set custom priority depending on some function of waiting time and job size?

**Comment by djordon** [comment]
Yes this is possible. The easiest way to accomplish such a task is to create a new `Agent` class and a new queue-server class that subclasses the `QueueServer` class but with its `queue` attribute changed. I'll give two examples to illustrate what needs to be done.

### Example 1
Let's create a queue that services queued agents in random order (an SIRO queue). First I would define a queue object for use within the queue-server:
```python
import random


class QueueSIRO:
    def __init__(self):
        self._queue = []

    def append(self, item):
        self._queue.append(item)

    def popleft(self):
        random.shuffle(self._queue)
        return self._queue.pop()

    def __len__(self):
        return len(self._queue)
```
As you can see, the above class just pops a random element when you call the `popleft` method; everything else about it is regular. Then to create our new queue-server we would subclass the original `QueueServer` class but just change it's internal `queue` attribute.
```python
import queueing_tool as qt


class QueueServerSIRO(qt.QueueServer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.queue = QueueSIRO()
```
The above queue-server is an SIRO queue-server (well at least it should be but I haven't tested it).

### Example 2

Now for your actual request. Let's assume that you have these agents that are created with job priorities and job sizes. This means that they get sent to the front of the line in the queue-server depending on their priority and then job size. Here we need to create an agent and the queue-server's queue:
```python
import random
import queueing_tool as qt


class JobAgent(qt.Agent):
    def __init__(self, priority, job_size, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.key = (priority, job_size)


class Queue4JobAgents:
    def __init__(self, sorter):
        self._queue = []
        self.sorter = sorter

    def append(self, item):
        self._queue.append(item)

    def popleft(self):
        self._queue.sort(key=self.sorter, reverse=True)
        return self._queue.pop()

    def __len__(self):
        return len(self._queue)
```
Note that if we have
```python
queue = Queue4JobAgents(lambda x: x.key)
```
then `queue` is just a list that sorts agents by priority and job size. Okay, next we need to define the queue server like we did above. But we also need to make sure that our queue-server only creates `JobAgent`s since our special queue class (`Queue4JobAgents`) expects incoming agents to have a `key` attribute (and regular `Agent`s do not have such an attribute).
```python
class QueueServerJob(qt.QueueServer):
    def __init__(self, sorter, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.queue = Queue4JobAgents(sorter)


def my_sorter(agent):
    return agent.key


def agent_factory(agent_id):
    priority = random.randint(0, 10)
    job_size = random.randint(10, 20)
    return JobAgent(priority, job_size, agent_id=agent_id)


# when creating our queue-server we need to remember to set the
# AgentFactory, which is responsible for creating arriving agents
queue_server = QueueServerjob(
    sorter=my_sorter,
    AgentFactory=agent_factory,
    # and of course you could set any other QueueServer
    # attributes/settings here
)
```
And now we have a queue-server that has the properties that we desire (well technically I don't know if I have some typo in here because I can't test it yet but it probably works)! 

You mentioned wanting to set the queue discipline to be involve a function of waiting time and perhaps some other attributes of the agent. For that you would do something like I did in Example 2, but with a different sorter function. Each agent has a `_time` attribute that is used as their arrival time and all agents in the queue-server's `queue` will have that attribute set. You can then write some sorter function that uses the `_time` attribute for sorting agents.

Hope this was reasonably clear and helpful!

**Comment by michalplat** [comment]
Thanks a lot for elaborated description of solution and instruction how to use agent factory! I have one concern though. By "job size" I meant how long it will be processed by server, so it should be somehow connected with server function. I checked code of queue_servers.py and I see that `next_event` method assign return of `service_f` to `_time` attribute after pop. If I understand correctly I need to rather define job_size like this:
```python
#I can overwrite _add_arrival to pass service_f to agent_factory and define service_f without "t" argument eg. as Exp(µ)
def agent_factory(agent_id, service_f):
    job_size = service_f()
    return JobAgent( job_size, agent_id=agent_id)
``` 
And now I should overwrite `next_event` to not call service_f second time for same agent:
```python
agent._time = agent.job_size + self._current_t
agent.queue_action(self, 1)
heappush(self._departures, agent)
```
Am I going to the right direction?

**Comment by djordon** [comment]
Yup, you're definitely going in the right direction, that should have the effect that you desire.

Note: you probably know this already but make sure the `agent_factory` function passed to the queue-server requires only one variable. I figured you added in the second variable to make it clearer to the reader where the `service_f` comes from but I thought I'd mention it anyway.

**Comment by michalplat** [comment]
Great :) Thank You for Your help, I think I can handle it now by myself.
