### ISSUE TITLE
Zeros in service and departure time present in queue data

### ISSUE THREAD

**Issue by spanchenko** [djordon/queueing-tool#69]
I simulate a simple network
`from numpy.random import uniform
g = nx.DiGraph()
g.add_node(0, type='generate')
g.add_node(1, type='advance')
g.add_node(2, type='terminate')

g.add_edge(0,1, edge_type=1)
g.add_edge(1,2, edge_type=2)
g.add_edge(2,2, edge_type=0)

def arr_f(t):
    return t + np.random.exponential(300)

def ser_f(t):
    return t + 330

q_classes = {1: qt.QueueServer, 2: qt.QueueServer}
q_args = {
    1: {
        'arrival_f': arr_f,
        'service_f': lambda t: t,
        'AgentFactory': qt.GreedyAgent
    },
    2: {
        'num_servers': 1,
        'service_f': ser_f
    }
}

qn = qt.QueueNetwork(g=g, q_classes=q_classes, q_args=q_args, seed=13)
qn.initialize(edge_type=1)
qn.clear_data()
qn.start_collecting_data()
qn.simulate(n=6000)
data = qn.get_queue_data(edge_type=2)
df = pd.DataFrame(data, columns=['arrival','service','departure','num_queued','num_total','q_id'])
df['waiting_time'] = df['service'] - df['arrival']
df['service_time'] = df['departure'] - df['service']
df.loc[np.argmin(df['waiting_time'])-10:np.argmin(df['waiting_time']), :]
`

and get zeros in `service` and `departure` time

<img width="670" alt="Screen Shot 2021-02-10 at 10 19 04" src="https://user-images.githubusercontent.com/1243913/107463978-77d3e880-6b89-11eb-8d35-154c23cd52b7.png">

Is it correct behavour or bug?

**Comment by djordon** [comment]
I'm believe those zeros represent agents that are in the system but are waiting in the line at the `QueueServer` so they don't have a service start time or a departure time, just an arrival time. If you look at `data` array, you can see where things left off. I ran your code and found the point to be in the slice `data[1850:1860]`.

So this is correct behavior. When you ask for queue data with `get_queue_data`, Queueing-tool creates an array with zeros and fills in actual data when it has it. I think queueing-tool could do something else here, specifically it could fill the array with `np.nan`s when we don't know the value.

In either case I need to do a better job at documenting this behavior because it's definitely confusing.

**Comment by spanchenko** [comment]
Thanks, I understood this in a few hours after submitting issue.
